import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as PDFImage, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

def generate_trip_pdf(trip_data, filename, image_path=None, weather_info=None):
    """
    Generates a rich PDF itinerary with Image and Weather.
    """
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # --- 1. Title ---
    destination = trip_data.get("destination", "Unknown Destination")
    title_style = ParagraphStyle(
        'MainTitle', parent=styles['Title'], fontSize=24, textColor=colors.darkblue, spaceAfter=20
    )
    story.append(Paragraph(f"Trip to {destination}", title_style))

    # --- 2. Main Image (If exists) ---
    if image_path and os.path.exists(image_path):
        try:
            # Load image, preserving aspect ratio (max width 6 inches, max height 4 inches)
            img = PDFImage(image_path, width=6*inch, height=4*inch)
            img.hAlign = 'CENTER'
            story.append(img)
            story.append(Spacer(1, 20))
        except Exception as e:
            print(f"⚠️ PDF Image Error: {e}")

    # --- 3. Info Strip (Weather | Vibe | Budget) ---
    budget = trip_data.get("budget", "N/A")
    vibe = trip_data.get("analyzed_vibe", "General")
    
    # Clean weather text (remove newlines if any)
    weather_clean = weather_info.replace("\n", " ") if weather_info else "N/A"

    # Create a nice data table
    data = [
        ["💰 Budget", "✨ Vibe", "🌤️ Weather"],
        [f"{budget}", f"{vibe}", f"{weather_clean}"]
    ]
    
    table = Table(data, colWidths=[2*inch, 2*inch, 2.5*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.aliceblue), # Header color
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.navy),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('BACKGROUND', (0, 1), (-1, 1), colors.whitesmoke), # Row color
        ('GRID', (0, 0), (-1, -1), 1, colors.white),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.lightgrey),
    ]))
    
    story.append(table)
    story.append(Spacer(1, 25))

    # --- 4. Summary ---
    summary = trip_data.get("summary", "")
    if summary:
        story.append(Paragraph("<b>Trip Summary:</b>", styles['Heading2']))
        story.append(Paragraph(summary, styles['Normal']))
        story.append(Spacer(1, 20))

    # --- 5. Itinerary ---
    story.append(Paragraph("Detailed Itinerary", styles['Heading2']))
    story.append(Spacer(1, 10))

    itinerary = trip_data.get("itinerary", [])
    
    for day_plan in itinerary:
        day_num = day_plan.get("day", "?")
        day_title = day_plan.get("title", "Day Plan")
        
        # Header for the day
        story.append(Paragraph(f"Day {day_num}: {day_title}", styles['Heading3']))
        
        # Activities
        activities = day_plan.get("activities", [])
        if isinstance(activities, list):
            for activity in activities:
                bullet_style = ParagraphStyle('Bullet', parent=styles['Normal'], leftIndent=20)
                story.append(Paragraph(f"• {activity}", bullet_style))
        
        story.append(Spacer(1, 10))

    # --- 6. Footer ---
    story.append(Spacer(1, 30))
    footer = Paragraph("<i>Generated by Smart Travel Agent AI</i>", styles['Italic'])
    story.append(footer)

    doc.build(story)
    print(f"✅ PDF generated: {filename}")